import React from 'react';
import './App.css';
import collegepic from './college_02.jpg';

export default class App extends React.Component{
  constructor(props){
    super(props)
    this.state={
    colleges: [
            {
                "college_name": "Hansraj College Delhi University - 1",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 2",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 3",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 4",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 5",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 6",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 7",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 8",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 9",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 10",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 11",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 12",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 13",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 14",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 15",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 16",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 17",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 18",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 19",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 20",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 21",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 22",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 23",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 24",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 25",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 26",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 27",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 28",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 29",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 30",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 31",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 32",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 33",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 34",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 35",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 36",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 37",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 38",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 39",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 40",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 41",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 42",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 43",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 44",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 45",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 46",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 47",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 48",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 49",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            },
            {
                "college_name": "Hansraj College Delhi University - 50",
                "promoted": true,
                "discount": 20,
                "original_fees": 6000,
                "discounted_fees": 5200,
                "fees_cycle": "Per Semester (3months)",
                "image": "college.png",
                "ranking": "7 in 260 colleges in north campus",
                "tags": ["best colleges in 2018", "2kms away"],
                "amenties": ["Fee cancellation", "Free Wifi"],
                "rating": 4,
                "rating_remarks": "Very Good",
                "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
                "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
                "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
            }
        ]
    

    }
  }
  render(){
    console.log(this.state.colleges)
    return(
      <React.Fragment>
          <div className="container">
            {this.state.colleges.map((val,index)=>{
             return(
            <div className="card">
                <div class="imagecard">
                    <div id="pointer">PROMOTED</div>
                        <img src={collegepic  } alt="Notebook" style={{width:"100%"}}></img>
                        <div class="content">
                         <div className="ratingstyle">
                         <p>3.9/5</p>
                        <p>Very Good</p>
                    </div> 
                <p style={{marginTop:"30%"}}><span className="bottomtext">Best College 2018</span><span className="bottomtext1">2kms away</span><span className="teststyle">#7 in 260 colleges in north campus</span></p>    
            </div>  
        <div>   
    </div>
    </div>

            <div style={{margin:"10px",color:"black",lineHeight:"0.5em"}}>
            <h4>{val.college_name}  <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star"></span>
                                    <span style={{float:"right"}}><del>₹68756</del></span></h4>
          <p style={{fontSize:"10px"}}>{val.nearest_place[0]} | {val.nearest_place[1]} <span style={{float:"right",color:"red",fontSize:"20px"}}><b>₹5768</b></span></p>
          <p style={{fontSize: "12px"}}>93% Match:{val.famous_nearest_places}<span style={{float:"right"}}>Per Semester(3month)</span></p>
          <p style={{marginTop:"6%", fontSize: "12px",fontWeight:"600"}}><span className="bottomtext3">Flat Rs <span style={{color:"#12b8a7"}}>2000</span> off+upto Rs <span style={{color:"#12b8a7"}}>500</span>  wallet!to avail...LOGIN</span><span style={{float:"right",color:"#12b8a7"}}>Free Cancelation +Free Wifi</span></p>
          </div> 
          </div>
          )
        })}
        </div>
      </React.Fragment>
    )
  }
}
